In [10]:
pip install ipykernel

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [11]:
pip show ipykernel

Name: ipykernel
Version: 7.1.0
Summary: IPython Kernel for Jupyter
Home-page: https://ipython.org
Author: 
Author-email: IPython Development Team <ipython-dev@scipy.org>
License-Expression: BSD-3-Clause
Location: C:\Users\DELL\AppData\Roaming\Python\Python313\site-packages
Requires: comm, debugpy, ipython, jupyter-client, jupyter-core, matplotlib-inline, nest-asyncio, packaging, psutil, pyzmq, tornado, traitlets
Required-by: jupyter, jupyter-console, jupyterlab
Note: you may need to restart the kernel to use updated packages.


In [ ]:
from typing import List,TypedDict,Literal
# when raw data try to enter in application by api(json format) pydantic validate it and possible convert it into suitable formate
from pydantic import BaseModel  
import re
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import FAISS    # vector DATABASE
from langchain_openai import OpenAIEmbeddings,ChatOpenAI
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate

from langgraph.graph import StateGraph,START,END
from dotenv import load_dotenv

load_dotenv()

In [ ]:
docs={
    PyPDFLoader("./documents/books1.pdf").load()
    PyPDFLoader("./documents/books")
}

In [15]:
import torch
import torch.nn as nn
import torch.optim as optim

# 1. BUILD THE ARCHITECTURE
class SimpleMLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleMLP, self).__init__()
        
        # Layer 1: The Hidden Layer (Connects Input -> Hidden)
        self.hidden_layer = nn.Linear(input_size, hidden_size)
        
        # The Non-Linear Activation Function (The secret sauce!)
        self.relu = nn.ReLU()
        
        # Layer 2: The Output Layer (Connects Hidden -> Output)
        self.output_layer = nn.Linear(hidden_size, output_size)

    # This defines how data flows FORWARD through the network
    def forward(self, x):
        x = self.hidden_layer(x)  # Math: Weights * Input + Bias
        x = self.relu(x)          # Bend the data (Non-linearity)
        x = self.output_layer(x)  # Final prediction
        return x

# --- SETTING UP THE AI ---

# Let's say we are predicting a house price based on 3 features (Bedrooms, Bathrooms, Age)
INPUT_FEATURES = 3
HIDDEN_NEURONS = 5
OUTPUT_PREDICTION = 1

# Initialize our model
model = SimpleMLP(INPUT_FEATURES, HIDDEN_NEURONS, OUTPUT_PREDICTION)

# Define the Loss Function (How we calculate the error)
# MSE (Mean Squared Error) is standard for predicting numbers
criterion = nn.MSELoss()

# Define the Optimizer (The Gradient Descent engine that updates the weights)
# Learning Rate (lr) is the size of the steps it takes to fix its mistakes
optimizer = optim.SGD(model.parameters(), lr=0.01)

# --- THE TRAINING LOOP ---

# Dummy Data: 1 house with 3 bedrooms, 2 baths, 10 years old
dummy_input = torch.tensor([[3.0, 2.0, 10.0]]) 
# The actual true price of the house (e.g., $300k)
true_answer = torch.tensor([[300.0]]) 

print("Starting Training...")

for epoch in range(5): # We will train it 5 times (epochs)
    
    # Step 1: Forward Pass (Make a guess)
    prediction = model(dummy_input)
    
    # Step 2: Calculate the Loss (How wrong was the guess?)
    loss = criterion(prediction, true_answer)
    
    # Step 3: Backpropagation (Calculate the gradients)
    optimizer.zero_grad() # Clear old gradients
    loss.backward()       # Figure out which weights caused the error
    
    # Step 4: Gradient Descent (Update the weights)
    optimizer.step()      
    
    print(f"Epoch {epoch+1} | AI's Guess: {prediction.item():.2f} | Loss (Error): {loss.item():.2f}")

print("Training Complete! Notice how the AI's guess gets closer to 300 each time.")

Starting Training...
Epoch 1 | AI's Guess: 0.38 | Loss (Error): 89773.04
Epoch 2 | AI's Guess: 347.78 | Loss (Error): 2283.09
Epoch 3 | AI's Guess: 5.34 | Loss (Error): 86824.88
Epoch 4 | AI's Guess: 11.23 | Loss (Error): 83386.61
Epoch 5 | AI's Guess: 17.01 | Loss (Error): 80084.51
Training Complete! Notice how the AI's guess gets closer to 300 each time.


In [3]:
import torch
import warnings
torch.__version__
torch.cuda.is_available()   # Check if CUDA (GPU support) is available
# if torch.cuda.is_available():
#     print(torch.cuda.get_device_name())
#     print("CUDA is available! You can train on the GPU for faster performance.")
# if not torch.cuda.is_available():
#     warnings.warn("CUDA is not available. Training will be slower on CPU.")

# torch.manual_seed(1)
torch.rand(2,3)
torch.empty(2,3)
torch.zeros(2,3)
torch.ones(2,3)
torch.randn(2,3)  # Random numbers from a normal distribution
torch.randint(0,10,(2,3))  # Random integers between 0 and 9
torch.tensor([[3,5,5,6],[2,3,4,5]])
torch.tensor([[2,3,4],[2,4,5]],dtype=torch.float64)
torch.tensor([[2,3,4],[2,4,5]],dtype=torch.float64).dtype

torch.linspace(0,1,5)  # 5 numbers evenly spaced between 0 and 1
torch.eye(4) # 4x4 Identity Matrix
torch.arange(0,10,2)  # Numbers from 0 to 9 with a step of 2
torch.rand(2,3)
torch.full((2,3),4)  # A 2x3 tensor filled with the value 4

# shape of a tensor
x=torch.rand(2,3)
x.shape
x.size()

# like wise tensor size
# torch.manual_seed(2)
xy= torch.rand(2,2)
# torch.empty_like(xy)
# torch.rand_like(x)
# torch.zeros_like(x)


torch.rand_like(xy)

x1=torch.tensor([[2,3],[45,5]])
torch.randint_like(x1,0,10)  # Random integers with the same shape as x1, between 0 and 9
# torch.full_like(x1,7)  # A tensor with the same shape as x1
# torch.rand_like(x1)  # float numbers  0 to 1
torch.rand_like(x1,dtype=torch.float64)

# type conversion
x1= torch.tensor([[23,34],[34,554]])
print(x1.dtype)
x1=x1.to(torch.float16)
print(x1.dtype)  # Still int64, because we didn't save the converted tensor
x=x1.to(torch.int64)

print(x)
print(x.dtype)
print(x+2)
print(x-3)
print(x*2)
print(x/2)  
# integer division (floor division)
print(x//2)

print((x*100)//3%2)

print(x**3)

torch.int64
torch.float16
tensor([[ 23,  34],
        [ 34, 554]])
torch.int64
tensor([[ 25,  36],
        [ 36, 556]])
tensor([[ 20,  31],
        [ 31, 551]])
tensor([[  46,   68],
        [  68, 1108]])
tensor([[ 11.5000,  17.0000],
        [ 17.0000, 277.0000]])
tensor([[ 11,  17],
        [ 17, 277]])
tensor([[0, 1],
        [1, 0]])
tensor([[    12167,     39304],
        [    39304, 170031464]])


MAtrix Operation   ## element wise operation

In [4]:
torch.manual_seed(0)
a= torch.randint(0,10,(2,2))
b= torch.randint(0,10,(2,2))
print(a)
print(b)
# # add
print('constant addition:',a+2)
print('matrix addition:',a+b)
print('matrix substraction:',a-b)
print('matrix multiplication:',a*b)

print('matrix division:',a/b)
print('matrix floor division:',a//b) 


a1=torch.tensor([-3200,-300])
print(torch.abs(a1))  # Absolute value
print(a1.abs())  # Absolute value  
print(torch.neg(a1))
print(a1.neg())  # Negation (flip the sign)

a11=torch.tensor([[-1,2],[-3,4]])
print(torch.abs(a11))

a11=torch.tensor([223.3,3.44,34.23,23.345])
print(torch.round(a11))  # Round to nearest
print(a11.round()) 
print(torch.floor(a11))  # Round down
print(a11.floor())
print(torch.ceil(a11))   # Round up

tensor([[4, 9],
        [3, 0]])
tensor([[3, 9],
        [7, 3]])
constant addition: tensor([[ 6, 11],
        [ 5,  2]])
matrix addition: tensor([[ 7, 18],
        [10,  3]])
matrix substraction: tensor([[ 1,  0],
        [-4, -3]])
matrix multiplication: tensor([[12, 81],
        [21,  0]])
matrix division: tensor([[1.3333, 1.0000],
        [0.4286, 0.0000]])
matrix floor division: tensor([[1, 1],
        [0, 0]])
tensor([3200,  300])
tensor([3200,  300])
tensor([3200,  300])
tensor([3200,  300])
tensor([[1, 2],
        [3, 4]])
tensor([223.,   3.,  34.,  23.])
tensor([223.,   3.,  34.,  23.])
tensor([223.,   3.,  34.,  23.])
tensor([223.,   3.,  34.,  23.])
tensor([224.,   4.,  35.,  24.])


In [5]:
print("Hello world")
d=torch.tensor([1.2,1.8,1.99,2,3,4,5])
torch.clamp(d,0,2)  # Clamp values to be between 0 and 2

Hello world


tensor([1.2000, 1.8000, 1.9900, 2.0000, 2.0000, 2.0000, 2.0000])

Reduction Operation

In [85]:
d=torch.tensor([[2,4,3],[1,5,1],[2,4,5]])
# d

d1=torch.randint(0,10,(3,3))
d1
d2=torch.randint(size=(4,4),low=10,high=20)
d2
torch.manual_seed(23)
# mannual_seed(23)
d3=torch.randint(4,10,(3,3))  # Random integers between 4 and 9, in a 3x3 shape
print(d3)
torch.sum(d3)
print(f"this is sum of each row {torch.sum(d3,dim=0):}")

n=0
for i in torch.sum(d3,dim=0):
    n+=1
    print(f"Row {n} sum:{i}")
print(f"This is Sum of Each column and set to row1, row2 =  {torch.sum(d3,dim=1)}")
n=0
for i in torch.sum(d3,dim=1):
    n+=1
    print(f"Column {n} sum:{i}")

print("Canot find mean of int, we need firslty each element of matrix in float32,float64 then will run perfectly")
# torch.mean(d3,dim=0)
# d31=d3.float()  # it convert each int element into float of d3

print("Type Conversion")
d4= d3.to(torch.float64)
d4.dtype

print(f" Rowise mean={torch.mean(d4,dim=0)}")

n=0
for i in torch.mean(d4,dim=0):
    n+=1
    print(f"Col {n}:{i}")
print(f"Column wise  mean of matrix: {torch.mean(d4,dim=1)}")

n=0
for i in torch.mean(d4,dim=1):
    n+=1
    print(f"Row {n}:{i}")

print(d3)
print(f"sum of every element of d3: {torch.sum(d3)}")
print(f"mean of every element of d4:{torch.mean(d4)}")
print(f"find the average of d4 matrix in round figure:{torch.round(torch.mean(d4),decimals=2)}")
n=torch.mean(d4).item()
print(f"{n:.10f}")
n2=torch.mean(d4)
print(f"{n2:.10f}")
torch.round(torch.mean(d4),decimals=4)

print(f"standdard Deviation of this matrix upto 3 decimal : {torch.round(torch.std(d4),decimals=3)}")

tensor([[7, 6, 4],
        [5, 6, 6],
        [5, 7, 4]])
this is sum of each row tensor([17, 19, 14])
Row 1 sum:17
Row 2 sum:19
Row 3 sum:14
This is Sum of Each column and set to row1, row2 =  tensor([17, 17, 16])
Column 1 sum:17
Column 2 sum:17
Column 3 sum:16
Canot find mean of int, we need firslty each element of matrix in float32,float64 then will run perfectly
Type Conversion
 Rowise mean=tensor([5.6667, 6.3333, 4.6667], dtype=torch.float64)
Col 1:5.666666666666667
Col 2:6.333333333333333
Col 3:4.666666666666667
Column wise  mean of matrix: tensor([5.6667, 5.6667, 5.3333], dtype=torch.float64)
Row 1:5.666666666666667
Row 2:5.666666666666667
Row 3:5.333333333333333
tensor([[7, 6, 4],
        [5, 6, 6],
        [5, 7, 4]])
sum of every element of d3: 50
mean of every element of d4:5.555555555555555
find the average of d4 matrix in round figure:5.56
5.5555555556
5.5555555556
standdard Deviation of this matrix upto 3 decimal : 1.13


In [121]:
print("To find the Median of array firstly need to sort them then find the middle element ")
print(d3)
print(f"Median=>middle element of each col after sorting :{torch.median(d3,dim=0)}")  # Median of each column
# torch.median(d3,dim=1) 


# torch.median(matrix,dim=0)  => mean sort matrix then find middle then give midean also with their orignal index

torch.manual_seed(34)
matrix= torch.tensor([[2,3,1],[4,5,7],[3,2,5]])
print(matrix)
torch.median(matrix)  # sort all element of matrix in 1D and then if number of element is even then find avg of two mind element
# median also giving the orignal indexing of element after performing sorting
torch.median(matrix,dim=0)
torch.median(matrix,dim=1)
torch.max(matrix,dim=0)
torch.min(matrix,dim=1)


mtrx=torch.tensor(((30,20),(10,10)),dtype=torch.float64)
print(torch.std(mtrx))
print(torch.var(mtrx))
torch.var(mtrx,dim=1)
torch.var(mtrx,dim=0)

To find the Median of array firstly need to sort them then find the middle element 
tensor([[7, 6, 4],
        [5, 6, 6],
        [5, 7, 4]])
Median=>middle element of each col after sorting :torch.return_types.median(
values=tensor([5, 6, 4]),
indices=tensor([2, 1, 2]))
tensor([[2, 3, 1],
        [4, 5, 7],
        [3, 2, 5]])
tensor(9.5743, dtype=torch.float64)
tensor(91.6667, dtype=torch.float64)


tensor([200.,  50.], dtype=torch.float64)

# MAtrix Operation
### should follow col=row property matmul,dot product for that number of element in both matrix should be same

In [ ]:
print(matrix)
torch.argmax(matrix,dim=0)  # gives the index of maximum value in each column

#<<<========================MATRIX MULTIPLICATION======================================>>>>
torch.manual_seed(34)
matrix1=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float64)
print(matrix1)

matrix2=torch.randint(0,10,(3,3),dtype=torch.float64)
print(matrix2)
print(f"this is matrix multiplication:{torch.matmul(matrix1,matrix2)}")

a = torch.tensor([[2,3,4],[3,2,3]]) # 2X3
b = torch.tensor([[2,4,1,0,9],[3,9,2,1,4],[3,4,5,7,8]]) # 3X5
print(f"This is also matrix mulitplication:{torch.matmul(a,b)}")

#<<<<===============================DOT Product========================================>>
# we need to firstly flatten to 1D array then each corresponding elemenet will be multiplied each otehr and only one scaller value ANS
#No of element in matrix1 == number of element in matrix2
matrix11=matrix1.flatten()
matrix22=matrix2.flatten()
print(f"flatten matrix1:{matrix11}")
print(f"flatten matrix2:{matrix22}")
a1=a.flatten()
b1=b.flatten()
print(f"This is Dot product and it will give only a scaller value:{torch.dot(matrix11,matrix22)}")
# print(f"This is Dot prodcut and its dot PRoduct will give scaller also:{torch.dot(a1,b1)}")

print(torch.matmul(a,b))

aa=torch.randint(0,10,(2,3,4),dtype=torch.float32)   # total Element=24
bb=torch.randint(0,10,(3,4,2),dtype=torch.float32)    # total element=23
print(f"First matrix:\n{aa}\n")
print(f"Second matrix:\n{bb}")
aa=aa.flatten()
bb=bb.flatten()
torch.dot(aa,bb)  # only a single scaller value


tensor([[3., 4., 2.],
        [3., 6., 7.],
        [0., 9., 1.]], dtype=torch.float64)
tensor([[3., 4., 2.],
        [3., 6., 7.],
        [0., 9., 1.]], dtype=torch.float64)
tensor([[9., 2., 4.],
        [7., 8., 5.],
        [9., 6., 5.]], dtype=torch.float64)
this is matrix multiplication:tensor([[ 73.,  50.,  42.],
        [132.,  96.,  77.],
        [ 72.,  78.,  50.]], dtype=torch.float64)
This is also matrix mulitplication:tensor([[25, 51, 28, 31, 62],
        [21, 42, 22, 23, 59]])
flatten matrix1:tensor([3., 4., 2., 3., 6., 7., 0., 9., 1.], dtype=torch.float64)
flatten matrix2:tensor([9., 2., 4., 7., 8., 5., 9., 6., 5.], dtype=torch.float64)
This is Dot product and it will give only a scaller value:206.0
tensor([[25, 51, 28, 31, 62],
        [21, 42, 22, 23, 59]])
First matrix:
tensor([[[4., 1., 8., 6.],
         [1., 2., 4., 1.],
         [6., 5., 9., 5.]],

        [[5., 9., 6., 2.],
         [9., 6., 1., 4.],
         [0., 2., 2., 5.]]])

Second matrix:
tensor([[[2., 4.],


tensor(473.)

# transpose

In [182]:
torch.manual_seed(34)
a=torch.randint(0,5,(3,3))
print(a)
a.transpose(0,1)

tensor([[3, 4, 2],
        [3, 1, 2],
        [0, 4, 1]])


tensor([[3, 3, 0],
        [4, 1, 4],
        [2, 2, 1]])